services:
  ya_service:
    container_name: yandex_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
      - "8081:8081"
    depends_on:
      - postgres
  postgres:
    container_name: postgres_container_ya
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres:
